### ISSUE TITLE
Kodiren gehigarrien biltegira gehitu

### ISSUE THREAD

**Issue by sukiletxe** [erral/plugin.video.eitb#2]
Interesgarria izango litzateke gehigarri hau Kodiren biltegitik bertatik jaitsi izatea, horrela erabiltzaile interesatuek errazago aurkituko bailukete. Hemen argibideak: <http://kodi.wiki/view/Submitting_Add-ons>

**Comment by erral** [comment]
Joan zen astean egon nintzen horri begira eta egin nituen aldaketa txiki batzuk.

Ea aste honetan egiten dudan.

**Comment by erral** [comment]
<del>Bidali dut gehigarrien biltegira. Hemen eskaera: https://github.com/xbmc/repo-plugins/pull/854</del>

**Comment by erral** [comment]
Hemen eskaera: https://github.com/xbmc/repo-plugins/pull/859

**Comment by erral** [comment]
Argitaratuta.
