### ISSUE TITLE
Plugin no longer functions

### ISSUE THREAD

**Issue by MartijnKaijser** [erral/plugin.video.eitb#4]
Going through the Kodi repo it seems you plugin no longer functions.
https://paste.ubuntu.com/p/64XGXtsHy4/

I have marked it broken for now to prevent installs

**Comment by erral** [comment]
I will try it again, but I was using the plugin last week without issues...

**Comment by erral** [comment]
@MartijnKaijser there was an issue with the backend server providing the API, which was timing-out, I have fixed the backend (there is no need to update the plugin), so can you unmark the plugin as broken?

**Comment by MartijnKaijser** [comment]
unmarked
